# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/codio/workspace/hw2/hw2_tests

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/codio/workspace/hw2/hw2_tests

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/codio/workspace/hw2/hw2_tests/CMakeFiles /home/codio/workspace/hw2/hw2_tests/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/codio/workspace/hw2/hw2_tests/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named testing_utils

# Build rule for target.
testing_utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testing_utils
.PHONY : testing_utils

# fast build rule for target.
testing_utils/fast:
	$(MAKE) -f testing_utils/CMakeFiles/testing_utils.dir/build.make testing_utils/CMakeFiles/testing_utils.dir/build
.PHONY : testing_utils/fast

#=============================================================================
# Target rules for targets named kwsys

# Build rule for target.
kwsys: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kwsys
.PHONY : kwsys

# fast build rule for target.
kwsys/fast:
	$(MAKE) -f testing_utils/kwsys/CMakeFiles/kwsys.dir/build.make testing_utils/kwsys/CMakeFiles/kwsys.dir/build
.PHONY : kwsys/fast

#=============================================================================
# Target rules for targets named perf

# Build rule for target.
perf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 perf
.PHONY : perf

# fast build rule for target.
perf/fast:
	$(MAKE) -f testing_utils/libperf/CMakeFiles/perf.dir/build.make testing_utils/libperf/CMakeFiles/perf.dir/build
.PHONY : perf/fast

#=============================================================================
# Target rules for targets named run_make_amazon

# Build rule for target.
run_make_amazon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_make_amazon
.PHONY : run_make_amazon

# fast build rule for target.
run_make_amazon/fast:
	$(MAKE) -f amazon_tests/CMakeFiles/run_make_amazon.dir/build.make amazon_tests/CMakeFiles/run_make_amazon.dir/build
.PHONY : run_make_amazon/fast

#=============================================================================
# Target rules for targets named amazon_tests

# Build rule for target.
amazon_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 amazon_tests
.PHONY : amazon_tests

# fast build rule for target.
amazon_tests/fast:
	$(MAKE) -f amazon_tests/CMakeFiles/amazon_tests.dir/build.make amazon_tests/CMakeFiles/amazon_tests.dir/build
.PHONY : amazon_tests/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... check"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... testing_utils"
	@echo "... kwsys"
	@echo "... perf"
	@echo "... run_make_amazon"
	@echo "... amazon_tests"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

